In [16]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD
# Importing function to normalize the data
from sklearn import preprocessing
from sklearn import metrics

In [17]:
df = pd.read_csv('merged-train-data.csv')
df[0::10000]

,Store,Dept,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,CPI,Unemployment,Type,Size,Markdowns,Year,Month,Day
0,1,1,24924.50,False,42.31,2.572,211.096358,8.106,A,151315,0.00,2010,2,5
10000,1,52,2373.49,False,68.55,3.617,223.181477,6.573,A,151315,15339.68,2012,10,5
20000,2,22,11627.47,False,75.88,3.717,222.217440,6.565,A,202307,19486.49,2012,9,14
30000,4,46,35567.04,False,55.19,2.743,126.606645,8.623,A,205863,0.00,2010,3,19
40000,5,20,1567.07,False,46.70,2.561,211.877147,6.566,B,34875,0.00,2010,2,26
50000,6,87,30535.15,False,78.89,2.759,212.412888,7.092,A,202505,0.00,2010,5,28
60000,7,32,4057.25,False,41.41,2.788,189.490412,8.963,B,70713,0.00,2010,5,14
70000,8,81,13873.38,False,75.71,2.705,214.542281,6.290,A,155078,0.00,2010,6,4
80000,9,91,1037.95,False,78.55,2.669,214.776503,6.442,B,125833,0.00,2010,7,2
90000,10,90,13731.97,False,85.75,2.939,126.190033,9.199,B,126512,0.00,2010,9,24
100000,11,91,40968.40,False,84.94,2.577,214.848169,7.346,A,207499,0.00,2010,9,3
110000,12,1,11995.69,True,83.63,3.044,126.114581,14.180,B,112238,0.00,2010,9,10
120000,13,38,75864.96,False,66.84,2.875,126.145467,7.951,A,219622,0.00,2010,9,17
130000,14,9,27392.23,False,78.44,2.805,182.622635,8.743,A,200898,0.00,2010,8,13
140000,15,10,11066.62,False,72.17,2.923,132.630000,8.099,B,123737,0.00,2010,8,13
150000,16,87,9120.80,False,58.02,2.773,190.362161,6.868,B,57197,0.00,2010,9,3
160000,17,16,2423.83,False,47.95,2.849,126.381548,6.885,B,93188,0.00,2010,10,22
170000,18,11,20683.15,False,42.05,2.938,132.924581,9.331,B,120653,0.00,2010,11,5
180000,19,42,6288.87,False,41.78,3.049,132.924581,8.067,A,203819,0.00,2010,11,5
190000,20,44,9471.84,False,50.52,2.917,205.062788,7.484,A,203742,0.00,2010,10,22
200000,21,52,2314.78,False,68.61,2.720,211.471329,8.163,B,140167,0.00,2010,10,15
210000,22,16,3126.69,True,44.61,3.070,136.689571,8.572,B,119557,0.00,2010,11,26
220000,23,54,291.60,False,23.05,3.139,132.680452,5.287,B,114533,0.00,2010,12,17
230000,24,98,8260.28,False,37.08,3.200,132.756667,8.275,A,203819,0.00,2010,12,3
240000,25,35,2933.64,True,43.43,3.039,204.962100,7.484,B,128107,0.00,2010,11,26
250000,26,26,6047.91,False,20.61,3.139,132.680452,8.149,A,152513,0.00,2010,12,17
260000,27,42,9069.25,False,31.62,3.301,136.529281,8.021,A,204184,0.00,2010,12,17
270000,28,80,17393.82,True,47.66,3.162,126.669267,14.313,A,206302,0.00,2010,11,26
280000,29,2,25654.13,False,28.43,3.132,132.676400,10.524,B,93638,0.00,2010,12,10
290000,30,21,1475.17,False,83.82,3.699,214.925487,7.931,C,42988,0.00,2011,6,3
300000,31,67,5729.66,False,69.79,3.274,217.004826,7.441,A,203750,0.00,2011,10,14
310000,32,8,24226.66,False,65.04,3.538,194.877972,8.622,A,203007,0.00,2011,9,30
320000,33,40,6837.84,False,100.07,3.811,130.756161,7.147,A,39690,368.93,2012,8,10
330000,34,21,3634.17,False,77.78,3.552,130.790968,9.285,A,158114,12640.69,2012,8,17
340000,35,71,9280.19,False,64.92,3.997,142.765750,8.839,B,103681,30619.14,2012,9,28
350000,37,31,11.38,False,84.43,3.637,213.748126,8.300,C,39910,0.00,2011,6,17
360000,38,96,14479.99,False,84.83,4.103,130.889677,11.627,C,39690,2502.30,2012,6,8
370000,39,14,20643.21,False,82.89,3.407,220.623405,6.623,A,184109,37988.59,2012,7,27
380000,40,13,20903.97,False,67.88,3.701,138.203387,4.156,A,155083,6741.85,2012,7,27
390000,41,16,23422.83,False,74.06,3.585,197.929038,6.432,A,196321,11150.14,2012,7,20
400000,43,91,30713.10,False,54.96,2.771,203.819129,10.210,C,41062,0.00,2010,11,19
410000,44,82,3693.90,True,33.73,3.116,130.384903,5.774,C,39910,4186.48,2012,2,10
420000,45,52,1326.03,False,66.30,3.848,190.996448,8.567,B,118221,10705.64,2012,5,18

In [18]:
feat = ['Store','Dept','IsHoliday','Temperature','Fuel_Price','CPI','Unemployment','Size','Markdowns','Year','Month','Day']
X = df[feat]
y = df['Weekly_Sales']
#preprocessing.scale(X)

In [19]:
# Performing PCA
# Total of 12 features, testing all reductions

for i in range(1,13):
    
    pca = PCA(n_components=i, whiten='True')
    new_X = pca.fit(X).transform(X)
    X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.3, random_state=2)
   
    lin_reg = LinearRegression()
    lin_reg.fit(X_train, y_train)
    print('\nFor', i, 'components, these are the results\n')
    print("Intercept: ", lin_reg.intercept_)
    print("Coefficient: " , lin_reg.coef_)
    
    y_pred = lin_reg.predict(X_test)
    mse = metrics.mean_squared_error(y_test,y_pred)
    rmse = np.sqrt(mse)
    print('RMSE',rmse)

For 1 components, these are the results

Intercept:  15957.913328325285
Coefficient:  [-5547.29293258]
RMSE 22152.94345407092

For 2 components, these are the results

Intercept:  15957.91024400184
Coefficient:  [-5547.18547704   324.44489952]
RMSE 22147.148036514092

For 3 components, these are the results

Intercept:  15958.191795031318
Coefficient:  [-5546.53983639   324.35410728  -479.48014132]
RMSE 22143.442087530068

For 4 components, these are the results

Intercept:  15959.046965760612
Coefficient:  [-5547.03735272   321.79802639  -485.54894302  3346.56052892]
RMSE 21878.916151542064

For 5 components, these are the results

Intercept:  15959.304845148916
Coefficient:  [-5546.59336311   321.99080971  -485.51302494  3347.0832722
  -412.56429701]
RMSE 21874.517021035437

For 6 components, these are the results

Intercept:  15958.255599520791
Coefficient:  [-5546.30777793   322.40816384  -485.8454754   3346.10362706
  -409.86633676 -1147.43287237]
RMSE 21846.076754959486

For 7 components, these are the results

Intercept:  15958.37749535751
Coefficient:  [-5546.27212954   322.28944212  -486.08229746  3345.90871686
  -409.87934752 -1147.40374965  -128.85791811]
RMSE 21845.95820862322

For 8 components, these are the results

Intercept:  15958.240411442144
Coefficient:  [-5546.73380735   323.16820096  -486.51458522  3345.90033421
  -411.18760169 -1147.33694785  -128.71562298   568.56513262]
RMSE 21836.167785667436

For 9 components, these are the results

Intercept:  15958.032462873036
Coefficient:  [-5546.69981246   322.97699121  -486.44134648  3345.85134798
  -411.01904613 -1147.08332406  -128.73849588   568.77728463
  -171.91636101]
RMSE 21835.43841747419

For 10 components, these are the results

Intercept:  15958.324086426079
Coefficient:  [-5547.16970019   323.70103928  -486.6757727   3345.93785723
  -411.51850631 -1146.58629504  -128.87962503   569.07326481
  -172.05187678   346.09495817]
RMSE 21832.227514715734

For 11 components, these are the results

Intercept:  15958.284381673702
Coefficient:  [-5547.26169554   323.54514863  -486.59218428  3345.85821505
  -411.50099426 -1146.49226439  -129.14917667   568.92946599
  -172.22962585   345.99893871   170.0255852 ]
RMSE 21831.95809073203

For 12 components, these are the results

Intercept:  15958.477403692877
Coefficient:  [-5547.26962796   324.06281296  -486.82312568  3345.8547327
  -411.60297141 -1146.43083096  -129.14539118   569.05812637
  -172.15747821   345.94807709   170.04868096   127.43909659]
RMSE 21830.53935050156

In [22]:
l = len(df['Weekly_Sales'])
sm = 0
mx = 0
for i in df['Weekly_Sales']:
    if i > mx:
        mx = i
    sm += i

avg = sm/l    

abvSum = 0
for i in df['Weekly_Sales']:
    if i > avg:
        abvSum  += 1

print('The maximum value for Weekly_Sales is:',mx)
print('The average Weekly_Sales are:',sm/l)
print('This is the amount of values that are over the average:',abvSum,'\nFrom a total of:', l, 'values.')

The maximum value for Weekly_Sales is: 693099.36
The average Weekly_Sales are: 15981.258123467327
This is the amount of values that are over the average: 130845
From a total of: 421570 values.